### ISSUE TITLE
Question about peernet.go

### ISSUE THREAD

**Issue by kbala444** [ipfs/bitswap-ml#4]
Are peernet (exchange/bitswap/testnet/peernet.go) and the virtual network (exchange/bitswap/testnet/virtual.go) interchangable?  Is there anything I have to consider when using it?  I tried using creating a peernet with a fully connected mocknet and using that as the argument for the NewTestSessionGenerator in testutils, but for some reason that I haven't been able to figure out this causes GetBlocks to never get any blocks.

**Comment by jbenet** [comment]
@heems i dont think so. am not super familiar with those-- want to show some example code that i can try debugging?

**Comment by kbala444** [comment]
I just figured it out actually!  I was just doing something stupid on my end haha
