### ISSUE TITLE
Data analysis/graphing tool for bssim

### ISSUE THREAD

**Issue by kbala444** [ipfs/bitswap-ml#7]
I don't think Prometheus fits our needs for bssim as its more of a monitoring tool than a data analysis tool.  It only graphs time series, so we'd be unable to graph, for example, the relationship between block times and latency.  It also aggregates and then scrapes data (individual data points are not preserved), making graphing harder.

I was thinking I could instead just use a MySQL (or postgres or something else maybe) database to store metrics and then use some plotting library for graphs.  I don't think this approach would be too hard, and it would be much more flexible.

**Comment by jbenet** [comment]
in that case use sqlite? want something that works without having to install + run other servers.
